import math
import os
from typing import Any, Dict, List, Optional

import requests


GOOGLE_MAPS_BASE_URL = "https://maps.googleapis.com/maps/api"


def get_google_maps_api_key() -> str:
    """Read the Google Maps API key from environment configuration."""
    return os.getenv("GOOGLE_MAPS_API_KEY", "")


def _request_json(url: str, params: Optional[Dict[str, Any]] = None, timeout: int = 5) -> Optional[Dict[str, Any]]:
    """Perform a GET request and return a parsed JSON object or None on failure."""
    try:
        response = requests.get(url, params=params, timeout=timeout)
        response.raise_for_status()
        payload = response.json()
        if isinstance(payload, dict) and payload.get("status") not in (None, "OK", "ZERO_RESULTS"):
            return None
        return payload
    except Exception:
        return None


def _haversine_distance_km(lat1: float, lng1: float, lat2: float, lng2: float) -> float:
    """Compute the haversine distance between two coordinates in kilometres."""
    radius_km = 6371.0
    lat1_rad = math.radians(lat1)
    lat2_rad = math.radians(lat2)
    delta_lat = math.radians(lat2 - lat1)
    delta_lng = math.radians(lng2 - lng1)

    a = (
        math.sin(delta_lat / 2) ** 2
        + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(delta_lng / 2) ** 2
    )
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return radius_km * c


def _build_fallback_hospitals(lat: float, lng: float, limit: int = 5) -> List[Dict[str, Any]]:
    """Create deterministic hospital fallback results when the Maps API is unavailable."""
    base = [
        {"name": "City General Hospital", "lat": lat + 0.004, "lng": lng + 0.002},
        {"name": "Sahara Medical Center", "lat": lat - 0.003, "lng": lng + 0.005},
        {"name": "Green Valley Clinic", "lat": lat + 0.002, "lng": lng - 0.004},
        {"name": "Medcare Trauma Unit", "lat": lat - 0.004, "lng": lng - 0.001},
    ]

    enriched = []
    for item in base[:limit]:
        distance = round(_haversine_distance_km(lat, lng, item["lat"], item["lng"]), 2)
        enriched.append(
            {
                "name": item["name"],
                "lat": item["lat"],
                "lng": item["lng"],
                "distance_km": distance,
                "eta_minutes": max(5, int(distance * 8)),
                "phone": None,
                "address": "Fallback location generated by Raksha AI",
            }
        )
    return enriched


def reverse_geocode(lat: float, lng: float) -> Dict[str, Any]:
    """Resolve a human-readable address for coordinates using Google Maps geocoding."""
    api_key = get_google_maps_api_key()

    if not api_key:
        return {
            "formatted_address": f"{lat}, {lng}",
            "address": f"Approximate location at {lat}, {lng}",
            "city": "Unknown",
            "state": "Unknown",
            "country": "Unknown",
            "source": "fallback",
        }

    payload = _request_json(
        f"{GOOGLE_MAPS_BASE_URL}/geocode/json",
        params={"latlng": f"{lat},{lng}", "key": api_key},
    )

    if not payload or not payload.get("results"):
        return {
            "formatted_address": f"{lat}, {lng}",
            "address": f"Approximate location at {lat}, {lng}",
            "city": "Unknown",
            "state": "Unknown",
            "country": "Unknown",
            "source": "fallback",
        }

    result = payload["results"][0]
    address_components = result.get("address_components", [])
    city = next((item["long_name"] for item in address_components if "locality" in item["types"]), "Unknown")
    state = next((item["long_name"] for item in address_components if "administrative_area_level_1" in item["types"]), "Unknown")
    country = next((item["long_name"] for item in address_components if "country" in item["types"]), "Unknown")

    return {
        "formatted_address": result.get("formatted_address", f"{lat}, {lng}"),
        "address": result.get("formatted_address", f"{lat}, {lng}"),
        "city": city,
        "state": state,
        "country": country,
        "source": "google_maps",
    }


def nearby_hospitals(lat: float, lng: float, radius_km: float = 5.0, limit: int = 5) -> List[Dict[str, Any]]:
    """Find nearby hospitals using Google Maps Places API with a fallback dataset."""
    api_key = get_google_maps_api_key()

    if not api_key:
        return _build_fallback_hospitals(lat, lng, limit=limit)

    radius_m = max(1000, int(radius_km * 1000))
    payload = _request_json(
        f"{GOOGLE_MAPS_BASE_URL}/place/nearbysearch/json",
        params={
            "location": f"{lat},{lng}",
            "radius": radius_m,
            "type": "hospital",
            "key": api_key,
        },
    )

    if not payload or not payload.get("results"):
        return _build_fallback_hospitals(lat, lng, limit=limit)

    hospitals = []
    for place in payload["results"][:limit]:
        place_lat = place.get("geometry", {}).get("location", {}).get("lat")
        place_lng = place.get("geometry", {}).get("location", {}).get("lng")

        if place_lat is None or place_lng is None:
            continue

        hospitals.append(
            {
                "name": place.get("name", "Unknown hospital"),
                "lat": place_lat,
                "lng": place_lng,
                "distance_km": round(_haversine_distance_km(lat, lng, place_lat, place_lng), 2),
                "eta_minutes": max(5, int(_haversine_distance_km(lat, lng, place_lat, place_lng) * 8)),
                "phone": place.get("formatted_phone_number"),
                "address": place.get("vicinity", "Address unavailable"),
            }
        )

    if hospitals:
        return hospitals

    return _build_fallback_hospitals(lat, lng, limit=limit)


__all__ = ["get_google_maps_api_key", "nearby_hospitals", "reverse_geocode"]
